name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install texlive
        run: |
          sudo apt -y install make texlive latexmk texlive-lang-cyrillic texlive-science texlive-latex-extra ttf-mscorefonts-installer
          sudo fc-cache -fv
      - name: Build pdf
        run: |
          cd man-source
          latexmk -pdf ./man-thesisby.tex
